{
    "instance": "u_reportl",
    "data": [
        {
            "sourceTable": "u_reportl",
            "sourceKey": "u_reportlstamp",
            "records": [
                {
                    "cellId": "004af785a06c6614fd11c5   ",
                    "coluna": "taxajuro",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "004af785a06c6614fd11c5   ",
                    "valor": "",
                    "campo": "saldo",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Taxa de Juro",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "digit",
                    "saldo": 0,
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Taxa de Juro",
                    "grupolordem": 0,
                    "u_reportlstamp": "004af785a06c6614fd11c5   ",
                    "rubrica": "taxajuro",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "0345eca55c4780707bd160   ",
                    "coluna": "origemfinanc",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "0345eca55c4780707bd160   ",
                    "valor": "",
                    "campo": "cvalor",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Origem do Financiamento",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "table",
                    "cvalor": "1900-01-01",
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Origem do Financiamento",
                    "grupolordem": 0,
                    "u_reportlstamp": "0345eca55c4780707bd160   ",
                    "rubrica": "origemfinanc",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "0b4e5e921bc4c303bcceb9   ",
                    "coluna": "desembolsoanual",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "0b4e5e921bc4c303bcceb9   ",
                    "valor": "",
                    "campo": "saldo",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Desembolso Anual",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "digit",
                    "saldo": 0,
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Desembolso Anual",
                    "grupolordem": 0,
                    "u_reportlstamp": "0b4e5e921bc4c303bcceb9   ",
                    "rubrica": "desembolsoanual",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "164f2881d3f00a3b018203   ",
                    "coluna": "financiador",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "164f2881d3f00a3b018203   ",
                    "valor": "",
                    "campo": "cvalor",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Financiador(es)",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "text",
                    "cvalor": "1900-01-01",
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Financiador(es)",
                    "grupolordem": 0,
                    "u_reportlstamp": "164f2881d3f00a3b018203   ",
                    "rubrica": "financiador",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "27469794cb6e3321a0135b   ",
                    "coluna": "observacoes",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "27469794cb6e3321a0135b   ",
                    "valor": "",
                    "campo": "cvalor",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Observações",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "textarea",
                    "cvalor": "1900-01-01",
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Observações",
                    "grupolordem": 0,
                    "u_reportlstamp": "27469794cb6e3321a0135b   ",
                    "rubrica": "observacoes",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "2d4476978064c790574747   ",
                    "coluna": "val",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "2d4476978064c790574747   ",
                    "valor": "",
                    "campo": "saldo",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Valor Actual Líquido (VAL)",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "digit",
                    "saldo": 0,
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Valor Actual Líquido (VAL)",
                    "grupolordem": 0,
                    "u_reportlstamp": "2d4476978064c790574747   ",
                    "rubrica": "val",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "2d47049731d2d624ebb4ed   ",
                    "coluna": "montantedesemb",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "2d47049731d2d624ebb4ed   ",
                    "valor": "",
                    "campo": "saldo",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Montante Desembolsado",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "digit",
                    "saldo": 0,
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Montante Desembolsado",
                    "grupolordem": 0,
                    "u_reportlstamp": "2d47049731d2d624ebb4ed   ",
                    "rubrica": "montantedesemb",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "2f4c9c87882fcda776937b   ",
                    "coluna": "montanteinvest",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "2f4c9c87882fcda776937b   ",
                    "valor": "",
                    "campo": "saldo",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Montante de Investimento",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "digit",
                    "saldo": 0,
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Montante de Investimento",
                    "grupolordem": 0,
                    "u_reportlstamp": "2f4c9c87882fcda776937b   ",
                    "rubrica": "montanteinvest",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "444ae383b89621af2b0f97   ",
                    "coluna": "duracao",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "444ae383b89621af2b0f97   ",
                    "valor": "",
                    "campo": "saldo",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Duração (anos)",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "digit",
                    "saldo": 0,
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Duração (anos)",
                    "grupolordem": 0,
                    "u_reportlstamp": "444ae383b89621af2b0f97   ",
                    "rubrica": "duracao",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "594d7a81db568657a2eb56   ",
                    "coluna": "datainicio",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "594d7a81db568657a2eb56   ",
                    "valor": "",
                    "campo": "cvalor",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Data de Início de Desembolso",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "date",
                    "cvalor": "1900-01-01",
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Data de Início de Desembolso",
                    "grupolordem": 0,
                    "u_reportlstamp": "594d7a81db568657a2eb56   ",
                    "rubrica": "datainicio",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "5d48d58a72638706ba645b   ",
                    "coluna": "tir",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "5d48d58a72638706ba645b   ",
                    "valor": "",
                    "campo": "saldo",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Taxa Interna de Retorno (TIR)",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "digit",
                    "saldo": 0,
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Taxa Interna de Retorno (TIR)",
                    "grupolordem": 0,
                    "u_reportlstamp": "5d48d58a72638706ba645b   ",
                    "rubrica": "tir",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "7447348ce4037308e7c7c5   ",
                    "coluna": "designacao",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "7447348ce4037308e7c7c5   ",
                    "valor": "",
                    "campo": "cvalor",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Designação do Projecto",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "text",
                    "cvalor": "",
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Designação do Projecto",
                    "grupolordem": 0,
                    "u_reportlstamp": "7447348ce4037308e7c7c5   ",
                    "rubrica": "designacao",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "754f51b354904f695a5504   ",
                    "coluna": "fontefinanc",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "754f51b354904f695a5504   ",
                    "valor": "",
                    "campo": "cvalor",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Fonte de Financiamento",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "table",
                    "cvalor": "1900-01-01",
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Fonte de Financiamento",
                    "grupolordem": 0,
                    "u_reportlstamp": "754f51b354904f695a5504   ",
                    "rubrica": "fontefinanc",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "994ea794428563d1e60e4b   ",
                    "coluna": "finalidade",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "994ea794428563d1e60e4b   ",
                    "valor": "",
                    "campo": "cvalor",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Finalidade",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "text",
                    "cvalor": "1900-01-01",
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Finalidade",
                    "grupolordem": 0,
                    "u_reportlstamp": "994ea794428563d1e60e4b   ",
                    "rubrica": "finalidade",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "a34eb49cb1eab36c237eb6   ",
                    "coluna": "localizacao",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "a34eb49cb1eab36c237eb6   ",
                    "valor": "",
                    "campo": "cvalor",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Localização (Província)",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "text",
                    "cvalor": "1900-01-01",
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Localização (Província)",
                    "grupolordem": 0,
                    "u_reportlstamp": "a34eb49cb1eab36c237eb6   ",
                    "rubrica": "localizacao",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "d04868b4e076d1b073ebdf   ",
                    "coluna": "taxaactualizacao",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "d04868b4e076d1b073ebdf   ",
                    "valor": "",
                    "campo": "saldo",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Taxa de Actualização",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "digit",
                    "saldo": 0,
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Taxa de Actualização",
                    "grupolordem": 0,
                    "u_reportlstamp": "d04868b4e076d1b073ebdf   ",
                    "rubrica": "taxaactualizacao",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                },
                {
                    "cellId": "f44f72ad7dbea6ce5a3912   ",
                    "coluna": "payback",
                    "rowid": "fc52b787-9e7a-478a-9377-d",
                    "sourceTable": "u_reportl",
                    "sourceKey": "u_reportlstamp",
                    "sourceKeyValue": "f44f72ad7dbea6ce5a3912   ",
                    "valor": "",
                    "campo": "saldo",
                    "linkid": "",
                    "linkField": "gruporowid",
                    "codigolinha": "u_reportl___1773959143",
                    "ordemField": "naturezaordem",
                    "descColuna": "Período de Retorno (Payback)",
                    "descColunaField": "descrubrica",
                    "cellIdField": "u_reportlstamp",
                    "rowIdField": "naturezasubrowid",
                    "colunaField": "rubrica",
                    "linhaField": "natureza",
                    "ordemColunaField": "grupolordem",
                    "ordemcoluna": 0,
                    "ordem": 1001,
                    "tipocolField": "tipocol",
                    "tipocol": "digit",
                    "saldo": 0,
                    "gruporowid": "",
                    "naturezaordem": 1001,
                    "natureza": "u_reportl___1773959143",
                    "descrubrica": "Período de Retorno (Payback)",
                    "grupolordem": 0,
                    "u_reportlstamp": "f44f72ad7dbea6ce5a3912   ",
                    "rubrica": "payback",
                    "naturezasubrowid": "fc52b787-9e7a-478a-9377-d",
                    "u_reportcstamp": "1"
                }
            ]
        }
    ]
}